# Cleaning Data

In [55]:
import pandas as pd

df = pd.read_csv('/Users/christianholm/Desktop/cyberbullying_tweets.csv')

df.columns = df.columns.str.strip()
df

                                              tweet_text cyberbullying_type
0      In other words #katandandre, your food was cra...  not_cyberbullying
1      Why is #aussietv so white? #MKR #theblock #ImA...  not_cyberbullying
2      @XochitlSuckkks a classy whore? Or more red ve...  not_cyberbullying
3      @Jason_Gio meh. :P  thanks for the heads up, b...  not_cyberbullying
4      @RudhoeEnglish This is an ISIS account pretend...  not_cyberbullying
...                                                  ...                ...
47687  Black ppl aren't expected to do anything, depe...          ethnicity
47688  Turner did not withhold his disappointment. Tu...          ethnicity
47689  I swear to God. This dumb nigger bitch. I have...          ethnicity
47690  Yea fuck you RT @therealexel: IF YOURE A NIGGE...          ethnicity
47691  Bro. U gotta chill RT @CHILLShrammy: Dog FUCK ...          ethnicity

[47692 rows x 2 columns]

In [56]:
# Apply a first round of text cleaning techniques
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

round1 = lambda x: clean_text_round1(x)

# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [57]:
clean_data = pd.DataFrame(df.tweet_text.apply(round1))
df['tweet_text'] = clean_data['tweet_text']

clean_data = pd.DataFrame(df.tweet_text.apply(round2))
df['tweet_text'] = clean_data['tweet_text']

In [38]:
df

                                              tweet_text cyberbullying_type
0      in other words katandandre your food was crapi...  not_cyberbullying
1      why is aussietv so white mkr theblock imaceleb...  not_cyberbullying
2      xochitlsuckkks a classy whore or more red velv...  not_cyberbullying
3      jasongio meh p  thanks for the heads up but no...  not_cyberbullying
4      rudhoeenglish this is an isis account pretendi...  not_cyberbullying
...                                                  ...                ...
47687  black ppl arent expected to do anything depend...          ethnicity
47688  turner did not withhold his disappointment tur...          ethnicity
47689  i swear to god this dumb nigger bitch i have g...          ethnicity
47690  yea fuck you rt therealexel if youre a nigger ...          ethnicity
47691  bro u gotta chill rt chillshrammy dog fuck kp ...          ethnicity

[47692 rows x 2 columns]

In [26]:
import pickle

df.to_pickle('datapickle.pkl')

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(df.tweet_text)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = df.index
data_dtm

/Users/christianholm/Desktop/SoftwareDevelopment/AAI/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aa,aaa,aaaa,aaaaa,aaaaaaaaaa,aaaaaaaaaaaaaaaaaaaaaah,aaaaaaaaaah,aaaaaaaaaajajajajajajajahahahajahaja,aaaaaaaahhhhhhh,aaaaah,...,𝕙𝕒𝕣𝕣𝕚𝕤𝕠𝕟,𝕠𝕘,𝕢𝕦𝕖𝕤𝕥𝕚𝕠𝕟,𝕣𝕠𝕟𝕟𝕚𝕖,𝕤𝕠𝕦𝕣𝕔𝕖,𝕥𝕙𝕖,𝕧𝕖𝕣𝕠𝕟𝕚𝕔𝕒,𝕨𝕠𝕦𝕝𝕕,𝕫𝕠𝕖𝕪,𝚎𝚕𝚞𝚜𝚒𝚟𝚎
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47689,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47690,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47691,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data_dtm.to_pickle("dtm.pkl")

In [11]:
pickle.dump(cv, open("cv.pkl", "wb"))

# Exploring Data

In [12]:
data = pd.read_pickle('dtm.pkl')
data = data.transpose()
data.head()

,0,1,2,3,4,5,6,7,8,9,...,47682,47683,47684,47685,47686,47687,47688,47689,47690,47691
aa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaaaaaaaaa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
subset1 = df[df['cyberbullying_type']=='gender']
text_gender = subset1.tweet_text.values

In [14]:
def get_top_n_words(corpus, n=None):
    """
    List the top n words in a vocabulary according to occurrence in a text corpus.
    """
    vec = CountVectorizer().fit(corpus)
    bag_of_words = vec.transform(corpus)
    sum_words = bag_of_words.sum(axis=0) 
    words_freq = [(word, sum_words[0, idx]) for word, idx in     vec.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1], reverse=True)

In [19]:
df

                                              tweet_text cyberbullying_type
0      in other words katandandre your food was crapi...  not_cyberbullying
1      why is aussietv so white mkr theblock imaceleb...  not_cyberbullying
2      xochitlsuckkks a classy whore or more red velv...  not_cyberbullying
3      jasongio meh p  thanks for the heads up but no...  not_cyberbullying
4      rudhoeenglish this is an isis account pretendi...  not_cyberbullying
...                                                  ...                ...
47687  black ppl arent expected to do anything depend...          ethnicity
47688  turner did not withhold his disappointment tur...          ethnicity
47689  i swear to god this dumb nigger bitch i have g...          ethnicity
47690  yea fuck you rt therealexel if youre a nigger ...          ethnicity
47691  bro u gotta chill rt chillshrammy dog fuck kp ...          ethnicity

[47692 rows x 2 columns]

# Michaels Guide

In [75]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/christianholm/nltk_data...
[nltk_data]   Unzipping corpora/omw-1.4.zip.

True

In [28]:
def remove_english_stopwords_func(text):
    '''
    Removes Stop Words (also capitalized) from a string, if present
    
    Args:
        text (str): String to which the function is to be applied, string
    
    Returns:
        Clean string without Stop Words
    ''' 
    # check in lowercase 
    t = [token for token in text if token.lower() not in stopwords.words("english")]
    text = ' '.join(t)    
    return text

In [29]:
def word_count_func(text):
    '''
    Counts words within a string
    
    Args:
        text (str): String to which the function is to be applied, string
    
    Returns:
        Number of words within a string, integer
    ''' 
    return len(text.split())

In [58]:
df['tweet_text_tokenized'] = df['tweet_text'].apply(word_tokenize)

In [59]:
df['Token_Count'] = df['tweet_text_tokenized'].str.len()

In [60]:
df['Word_Count'] = df['tweet_text'].apply(word_count_func)

In [42]:
df

,tweet_text,cyberbullying_type,tweet_text_tokenized,Token_Count,Word_Count
0,in other words katandandre your food was crapi...,not_cyberbullying,"[in, other, words, katandandre, your, food, wa...",9,9
1,why is aussietv so white mkr theblock imaceleb...,not_cyberbullying,"[why, is, aussietv, so, white, mkr, theblock, ...",13,13
2,xochitlsuckkks a classy whore or more red velv...,not_cyberbullying,"[xochitlsuckkks, a, classy, whore, or, more, r...",9,9
3,jasongio meh p thanks for the heads up but no...,not_cyberbullying,"[jasongio, meh, p, thanks, for, the, heads, up...",18,18
4,rudhoeenglish this is an isis account pretendi...,not_cyberbullying,"[rudhoeenglish, this, is, an, isis, account, p...",18,18
...,...,...,...,...,...
47687,black ppl arent expected to do anything depend...,ethnicity,"[black, ppl, arent, expected, to, do, anything...",42,42
47688,turner did not withhold his disappointment tur...,ethnicity,"[turner, did, not, withhold, his, disappointme...",45,45
47689,i swear to god this dumb nigger bitch i have g...,ethnicity,"[i, swear, to, god, this, dumb, nigger, bitch,...",20,20
47690,yea fuck you rt therealexel if youre a nigger ...,ethnicity,"[yea, fuck, you, rt, therealexel, if, youre, a...",15,15
47691,bro u gotta chill rt chillshrammy dog fuck kp ...,ethnicity,"[bro, u, got, ta, chill, rt, chillshrammy, dog...",15,14

In [61]:
df['tweet_no_Stop_Words'] = df['tweet_text_tokenized'].apply(remove_english_stopwords_func)

In [62]:
df['tweet_stop_word_count'] = df['tweet_no_Stop_Words'].apply(word_count_func)

In [63]:
df

,tweet_text,cyberbullying_type,tweet_text_tokenized,Token_Count,Word_Count,tweet_no_Stop_Words,tweet_stop_word_count
0,in other words katandandre your food was crapi...,not_cyberbullying,"[in, other, words, katandandre, your, food, wa...",9,9,words katandandre food crapilicious mkr,5
1,why is aussietv so white mkr theblock imaceleb...,not_cyberbullying,"[why, is, aussietv, so, white, mkr, theblock, ...",13,13,aussietv white mkr theblock imacelebrityau tod...,10
2,xochitlsuckkks a classy whore or more red velv...,not_cyberbullying,"[xochitlsuckkks, a, classy, whore, or, more, r...",9,9,xochitlsuckkks classy whore red velvet cupcakes,6
3,jasongio meh p thanks for the heads up but no...,not_cyberbullying,"[jasongio, meh, p, thanks, for, the, heads, up...",18,18,jasongio meh p thanks heads concerned another ...,10
4,rudhoeenglish this is an isis account pretendi...,not_cyberbullying,"[rudhoeenglish, this, is, an, isis, account, p...",18,18,rudhoeenglish isis account pretending kurdish ...,9
...,...,...,...,...,...,...,...
47687,black ppl arent expected to do anything depend...,ethnicity,"[black, ppl, arent, expected, to, do, anything...",42,42,black ppl arent expected anything depended any...,22
47688,turner did not withhold his disappointment tur...,ethnicity,"[turner, did, not, withhold, his, disappointme...",45,45,turner withhold disappointment turner called c...,29
47689,i swear to god this dumb nigger bitch i have g...,ethnicity,"[i, swear, to, god, this, dumb, nigger, bitch,...",20,20,swear god dumb nigger bitch got bleach hair re...,13
47690,yea fuck you rt therealexel if youre a nigger ...,ethnicity,"[yea, fuck, you, rt, therealexel, if, youre, a...",15,15,yea fuck rt therealexel youre nigger fucking u...,11
47691,bro u gotta chill rt chillshrammy dog fuck kp ...,ethnicity,"[bro, u, got, ta, chill, rt, chillshrammy, dog...",15,14,bro u got ta chill rt chillshrammy dog fuck kp...,14

In [64]:
df.head().T

,0,1,2,3,4
tweet_text,in other words katandandre your food was crapi...,why is aussietv so white mkr theblock imaceleb...,xochitlsuckkks a classy whore or more red velv...,jasongio meh p thanks for the heads up but no...,rudhoeenglish this is an isis account pretendi...
cyberbullying_type,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying
tweet_text_tokenized,"[in, other, words, katandandre, your, food, wa...","[why, is, aussietv, so, white, mkr, theblock, ...","[xochitlsuckkks, a, classy, whore, or, more, r...","[jasongio, meh, p, thanks, for, the, heads, up...","[rudhoeenglish, this, is, an, isis, account, p..."
Token_Count,9,13,9,18,18
Word_Count,9,13,9,18,18
tweet_no_Stop_Words,words katandandre food crapilicious mkr,aussietv white mkr theblock imacelebrityau tod...,xochitlsuckkks classy whore red velvet cupcakes,jasongio meh p thanks heads concerned another ...,rudhoeenglish isis account pretending kurdish ...
tweet_stop_word_count,5,10,6,10,9

# Stemming, Normalizing, NER & POS

In [66]:
from nltk.corpus import wordnet
from nltk import pos_tag
from nltk import ne_chunk

from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

from nltk.probability import FreqDist
import matplotlib.pyplot as plt

In [67]:
def norm_stemming_func(text):
    '''
    Stemming tokens from string
    
    Step 1: Use word_tokenize() to get tokens from string
    Step 2: Use PorterStemmer() to stem the created tokens
    
    Args:
        text (str): String to which the functions are to be applied, string
    
    Returns:
        String with stemmed words
    '''  
    words = word_tokenize(text)
    text = ' '.join([PorterStemmer().stem(word) for word in words])
    return text

In [73]:
def norm_lemm_v_a_func(text):
    '''
    Lemmatize tokens from string
    
    Step 1: Use word_tokenize() to get tokens from string
    Step 2: Use WordNetLemmatizer() with POS tag 'v' to lemmatize the created tokens
    Step 3: Use word_tokenize() to get tokens from generated string        
    Step 4: Use WordNetLemmatizer() with POS tag 'a' to lemmatize the created tokens
    
    Args:
        text (str): String to which the functions are to be applied, string
    
    Returns:
        String with lemmatized words
    '''
    words1 = word_tokenize(text)
    text1 = ' '.join([WordNetLemmatizer().lemmatize(word, pos='v') for word in words1])
    words2 = word_tokenize(text1)
    text2 = ' '.join([WordNetLemmatizer().lemmatize(word, pos='a') for word in words2])
    return text2

In [76]:
df['tweets_lemmatized'] = df['tweet_no_Stop_Words'].apply(norm_lemm_v_a_func)

df['Word_Count_lemmatized_tweet'] = df['tweets_lemmatized'].apply(word_count_func)

In [78]:
df['tweet_stemming'] = df['tweet_no_Stop_Words'].apply(norm_stemming_func)

,tweet_text,cyberbullying_type,tweet_text_tokenized,Token_Count,Word_Count,tweet_no_Stop_Words,tweet_stop_word_count,tweets_lemmatized,Word_Count_lemmatized_tweet
0,in other words katandandre your food was crapi...,not_cyberbullying,"[in, other, words, katandandre, your, food, wa...",9,9,words katandandre food crapilicious mkr,5,word katandandre food crapilicious mkr,5
1,why is aussietv so white mkr theblock imaceleb...,not_cyberbullying,"[why, is, aussietv, so, white, mkr, theblock, ...",13,13,aussietv white mkr theblock imacelebrityau tod...,10,aussietv white mkr theblock imacelebrityau tod...,10
2,xochitlsuckkks a classy whore or more red velv...,not_cyberbullying,"[xochitlsuckkks, a, classy, whore, or, more, r...",9,9,xochitlsuckkks classy whore red velvet cupcakes,6,xochitlsuckkks classy whore red velvet cupcakes,6

In [80]:
df.head(7).T

,0,1,2,3,4,5,6
tweet_text,in other words katandandre your food was crapi...,why is aussietv so white mkr theblock imaceleb...,xochitlsuckkks a classy whore or more red velv...,jasongio meh p thanks for the heads up but no...,rudhoeenglish this is an isis account pretendi...,quickieleaks yes the test of god is that good...,itu sekolah ya bukan tempat bully ga jauh kaya...
cyberbullying_type,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying,not_cyberbullying
tweet_text_tokenized,"[in, other, words, katandandre, your, food, wa...","[why, is, aussietv, so, white, mkr, theblock, ...","[xochitlsuckkks, a, classy, whore, or, more, r...","[jasongio, meh, p, thanks, for, the, heads, up...","[rudhoeenglish, this, is, an, isis, account, p...","[quickieleaks, yes, the, test, of, god, is, th...","[itu, sekolah, ya, bukan, tempat, bully, ga, j..."
Token_Count,9,13,9,18,18,22,10
Word_Count,9,13,9,18,18,22,10
tweet_no_Stop_Words,words katandandre food crapilicious mkr,aussietv white mkr theblock imacelebrityau tod...,xochitlsuckkks classy whore red velvet cupcakes,jasongio meh p thanks heads concerned another ...,rudhoeenglish isis account pretending kurdish ...,quickieleaks yes test god good bad indifferent...,itu sekolah ya bukan tempat bully ga jauh kaya...
tweet_stop_word_count,5,10,6,10,9,12,10
tweets_lemmatized,word katandandre food crapilicious mkr,aussietv white mkr theblock imacelebrityau tod...,xochitlsuckkks classy whore red velvet cupcakes,jasongio meh p thank head concern another angr...,rudhoeenglish isis account pretend kurdish acc...,quickieleaks yes test god good bad indifferent...,itu sekolah ya bukan tempat bully ga jauh kaya...
Word_Count_lemmatized_tweet,5,10,6,10,9,12,10